services:
  maptoposter:
    image: ghcr.io/alivebe-a11y/maptoposter-dock:latest
    container_name: maptoposter
    ports:
      - "5025:5025"
    volumes:
      # Local directory to retrieve generated PNGs
      - ./posters:/app/posters
    restart: unless-stopped
